-- Boomtown Platform — Migration 0001: Phase 1 foundation schema
-- Version: v0.1 · Date: 2026-07-21
-- STATUS: ALREADY APPLIED to D1 "boomtown-prod" (6cde5d11-4199-4e57-b10f-2b7e968264ea) on 2026-07-21.
-- Kept in the repo as the schema of record. Do NOT re-run against prod.
-- Conventions: org_id on every business table; soft delete via deleted_at; audit_log for changes.
-- Deferred to Phase 2/3 migrations: league_weeks, sub_requests, messages, segments, email_campaigns.

-- Full CREATE TABLE statements are documented below.

CREATE TABLE orgs (id INTEGER PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, logo_url TEXT, brand_json TEXT DEFAULT '{}', email_sender_name TEXT, email_sender_address TEXT, square_location_id TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE COLLATE NOCASE, display_name TEXT, totp_secret TEXT, totp_enabled INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE user_org_roles (user_id INTEGER NOT NULL REFERENCES users(id), org_id INTEGER NOT NULL REFERENCES orgs(id), role TEXT NOT NULL CHECK (role IN ('admin','staff','member')), created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT, PRIMARY KEY (user_id, org_id));
CREATE TABLE magic_links (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL COLLATE NOCASE, token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL REFERENCES users(id), token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE audit_log (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER, actor_user_id INTEGER, action TEXT NOT NULL, entity TEXT NOT NULL, entity_id TEXT, detail_json TEXT DEFAULT '{}', created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE contacts (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), user_id INTEGER REFERENCES users(id), email TEXT COLLATE NOCASE, full_name TEXT, phone TEXT, city TEXT, state TEXT, instagram TEXT, tags_json TEXT DEFAULT '[]', unsubscribed INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE INDEX idx_contacts_org_email ON contacts(org_id, email);
CREATE TABLE profiles (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), contact_id INTEGER NOT NULL REFERENCES contacts(id), photo_url TEXT, positions TEXT, skill_level TEXT, gender_division TEXT, height_reach TEXT, bio TEXT, privacy_tier TEXT NOT NULL DEFAULT 'hidden' CHECK (privacy_tier IN ('public','members-only','hidden')), created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE waivers (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), contact_id INTEGER NOT NULL REFERENCES contacts(id), waiver_text_version TEXT NOT NULL DEFAULT 'v1', signed_at TEXT NOT NULL, expires_at TEXT NOT NULL, signature_name TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE events (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), type TEXT NOT NULL CHECK (type IN ('tournament','league','training','event','court_rental')), name TEXT NOT NULL, starts_at TEXT, ends_at TEXT, location TEXT, capacity INTEGER, court_count INTEGER, format_template TEXT, config_json TEXT DEFAULT '{}', status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','in_progress','completed','cancelled')), cash_option_enabled INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE INDEX idx_events_org_status ON events(org_id, status);
CREATE TABLE form_fields (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), event_id INTEGER REFERENCES events(id), label TEXT NOT NULL, field_type TEXT NOT NULL CHECK (field_type IN ('text','email','phone','select','checkbox','file','textarea')), options_json TEXT DEFAULT '[]', required INTEGER NOT NULL DEFAULT 0, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE teams (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), event_id INTEGER NOT NULL REFERENCES events(id), name TEXT NOT NULL, level TEXT, gender_division TEXT, captain_contact_id INTEGER REFERENCES contacts(id), seed INTEGER, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE team_members (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), team_id INTEGER NOT NULL REFERENCES teams(id), contact_id INTEGER REFERENCES contacts(id), member_name TEXT, member_email TEXT, is_sub INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE registrations (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), event_id INTEGER NOT NULL REFERENCES events(id), contact_id INTEGER REFERENCES contacts(id), team_id INTEGER REFERENCES teams(id), status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','email-sent','paid','cash-pending','comped','cancelled')), payment_method TEXT CHECK (payment_method IN ('square','cash','comp') OR payment_method IS NULL), square_order_id TEXT, waiver_id INTEGER REFERENCES waivers(id), created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE INDEX idx_registrations_event_status ON registrations(event_id, status);
CREATE TABLE form_responses (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), registration_id INTEGER NOT NULL REFERENCES registrations(id), field_id INTEGER REFERENCES form_fields(id), field_label TEXT, value TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE pools (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), event_id INTEGER NOT NULL REFERENCES events(id), name TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE matches (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), event_id INTEGER NOT NULL REFERENCES events(id), pool_id INTEGER REFERENCES pools(id), stage TEXT NOT NULL DEFAULT 'pool' CHECK (stage IN ('pool','quarter','semi','final')), round INTEGER NOT NULL, court INTEGER NOT NULL, team_a_id INTEGER REFERENCES teams(id), team_b_id INTEGER REFERENCES teams(id), ref_team_id INTEGER REFERENCES teams(id), points_to INTEGER NOT NULL DEFAULT 21, cap INTEGER NOT NULL DEFAULT 23, game_number INTEGER NOT NULL DEFAULT 1, score_a INTEGER, score_b INTEGER, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE INDEX idx_matches_event_round ON matches(event_id, round, court);
CREATE TABLE standings (org_id INTEGER NOT NULL REFERENCES orgs(id), event_id INTEGER NOT NULL REFERENCES events(id), team_id INTEGER NOT NULL REFERENCES teams(id), wins INTEGER NOT NULL DEFAULT 0, losses INTEGER NOT NULL DEFAULT 0, point_diff INTEGER NOT NULL DEFAULT 0, points_for INTEGER NOT NULL DEFAULT 0, points_against INTEGER NOT NULL DEFAULT 0, rank INTEGER, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT, PRIMARY KEY (event_id, team_id));
CREATE TABLE brackets (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), event_id INTEGER NOT NULL REFERENCES events(id), name TEXT NOT NULL DEFAULT 'A', split_rule TEXT, config_json TEXT DEFAULT '{}', created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE payments (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), registration_id INTEGER REFERENCES registrations(id), square_payment_id TEXT UNIQUE, square_order_id TEXT, amount_cents INTEGER, currency TEXT DEFAULT 'USD', status TEXT, raw_json TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE discounts (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), code TEXT NOT NULL, kind TEXT NOT NULL CHECK (kind IN ('percent','fixed')), amount INTEGER NOT NULL, usage_cap INTEGER, used_count INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE checkins (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), event_id INTEGER REFERENCES events(id), contact_id INTEGER REFERENCES contacts(id), method TEXT CHECK (method IN ('qr','pin','admin')), checked_in_at TEXT NOT NULL DEFAULT (datetime('now')), created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);
CREATE TABLE notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id INTEGER NOT NULL REFERENCES orgs(id), kind TEXT NOT NULL, target TEXT, payload_json TEXT DEFAULT '{}', sent_at TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), deleted_at TEXT);

-- Seed data (applied)
INSERT INTO orgs (id, name, slug, brand_json) VALUES
 (1,'Boomtown Volleyball','boomtown','{"accent_dark":"#D4AF37","accent_light":"#1B2A4A"}'),
 (2,'Match Point Social','match-point','{"accent_dark":"#D4AF37","accent_light":"#1B2A4A"}'),
 (3,'Queens Club','queens-club','{"accent_dark":"#D4AF37","accent_light":"#1B2A4A"}');
