/* Boomtown Platform — page structure guard
   File: worker/test/page_structure.test.mjs · Version: v1.0 · Date: 2026-08-03 · Ships in: v0.66.0

   WHY THIS EXISTS. New admin pages in this repo are generated by slicing the shell off an existing
   page: take everything above <main>, insert the new <main>, keep everything from </main> down. If
   the source page already carries a stray </main>, the new page inherits it AND adds one. Nobody
   notices, because a browser silently discards a </main> with no matching open tag — so the page
   looks perfect and the defect compounds every release.

   By v0.65.0 five pages were affected and the count was climbing: member-fields 4, staff-pay 4,
   tryouts 3, passes 2, and the freshly generated schedule editor 5. Each was a copy of the last
   one's mistake plus one. This guard stops the chain at the next generation rather than after
   another five releases of quiet growth.

   It scans the WIDEST set — every HTML file that ships — because a guard narrower than its subject
   reports clean while the thing it was meant to catch happens somewhere it was not looking. */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("../../", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");

function shippedPages() {
  const found = [];
  for (const f of readdirSync(join(ROOT, "web"))) {
    if (f.endsWith(".html")) found.push(join("web", f));
  }
  for (const f of readdirSync(ROOT)) {
    if (f.endsWith(".html")) found.push(f);
  }
  return found.sort();
}

const PAGES = shippedPages();
const count = (s, re) => (s.match(re) || []).length;

test("the guard is actually scanning pages", () => {
  // A scanner that silently finds nothing is the most comfortable kind of broken.
  assert.ok(PAGES.length >= 40, `expected the full page set, found ${PAGES.length}`);
});

test("<main> is balanced on every page, and never appears twice", () => {
  // Not "exactly one": `index.html` is a five-line redirect stub with no landmark at all, and that
  // is correct. The defect being guarded is an UNBALANCED or DUPLICATED tag, which is what the
  // shell-slice produces.
  const bad = [];
  for (const p of PAGES) {
    const src = readFileSync(join(ROOT, p), "utf8");
    const open = count(src, /<main[\s>]/g);
    const close = count(src, /<\/main>/g);
    if (open !== close || close > 1) bad.push(`${p}: ${open} open, ${close} close`);
  }
  assert.deepEqual(bad, [], "unbalanced <main> — almost certainly a shell-slice that inherited a stray tag");
});

test("no page carries two closing tags in a row for the same landmark", () => {
  // The exact shape the shell-slice produces: </main> immediately followed by </main>.
  const bad = [];
  for (const p of PAGES) {
    const src = readFileSync(join(ROOT, p), "utf8");
    for (const tag of ["main", "aside", "nav", "header", "footer", "body", "html"]) {
      if (new RegExp(`</${tag}>\\s*</${tag}>`).test(src)) bad.push(`${p}: doubled </${tag}>`);
    }
  }
  assert.deepEqual(bad, []);
});

test("NC: the scanner can fail — a doubled tag in real page text is caught", () => {
  // Mutate a real page's real content, not a synthetic string, and confirm both checks trip.
  const p = PAGES.find((x) => x.includes("admin-schedule-editor")) || PAGES[0];
  const src = readFileSync(join(ROOT, p), "utf8");
  const mutated = src.replace("</main>", "</main>\n    </main>");
  assert.notEqual(mutated, src, "the mutation must actually change the file text");
  assert.equal(count(mutated, /<\/main>/g), 2, "the balance check would see 2 and fail");
  assert.ok(/<\/main>\s*<\/main>/.test(mutated), "the doubled-tag check would match and fail");
});
